### ISSUE TITLE
tinker_io-1.12.2-rw2.8.3(1.12.2) FuelInputMachine RuntimeException: Missing

### ISSUE THREAD

**Issue by cwc02777** [gkbm2013/tinker-IO#101]
GKB大大您好 我在使用燃料輸入機的時候
在兩種狀況下都會噴 RuntimeException

1. 打破燃料輸入機時
2. 燃料輸入機作用時(熔爐裡有東西可稍消耗燃料的時候)

其中一段訊息為:
	at tinker_io.network.NetworkHandler.sendToServer(NetworkHandler.java:26) [NetworkHandler.class:?]
	at tinker_io.tileentity.TileEntityFuelInputMachine.setSmelteryTemp(TileEntityFuelInputMachine.java:175) [TileEntityFuelInputMachine.class:?]
	at tinker_io.tileentity.TileEntityFuelInputMachine.resetTemp(TileEntityFuelInputMachine.java:206) [TileEntityFuelInputMachine.class:?]
	at tinker_io.tileentity.TileEntityFuelInputMachine.burnSolidFuel(TileEntityFuelInputMachine.java:98) [TileEntityFuelInputMachine.class:?]
	at tinker_io.tileentity.TileEntityFuelInputMachine.func_73660_a(TileEntityFuelInputMachine.java:62) [TileEntityFuelInputMachine.class:?]

伺服器訊息
 -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows Server 2016 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4687134736 bytes (4470 MB) / 6979321856 bytes (6656 MB) up to 6979321856 bytes (6656 MB)
	JVM Flags: 3 total; -Xms6656M -Xmx6656M -XX:+UseG1GC
	IntCache: cache: 1, tcache: 1, allocated: 14, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 102 mods loaded, 102 mods active

詳細Log 如附件 我有打字來區隔以上兩次exception(但看起來都一樣)
[exception.log](https://github.com/gkbm2013/tinker-IO/files/5646785/exception.log)

**Comment by gkbm2013** [comment]
謝謝你的回覆，我有在CurseForge收到你的訊息了，我會找時間處理一下~ 謝謝~
