### ISSUE TITLE
ArrayIndexOutOfBoundsException crash on connection with TD Fluiducts

### ISSUE THREAD

**Issue by bigbantha** [gkbm2013/tinker-IO#2]
Crashed when connecting a fluiduct to the Smart Output-thingy (honestly, I think it should be renamed because it doesn't really output anything).

java.lang.ArrayIndexOutOfBoundsException: 0
    at tinker_io.TileEntity.SOTileEntity.setLiquid(SOTileEntity.java:410)
    at tinker_io.TileEntity.SOTileEntity.func_145845_h(SOTileEntity.java:664)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1994)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by gkbm2013** [comment]
I have already fixed the bug. Thanks for your report!
