### ISSUE TITLE
[rw 2.7.0] StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by C0rn3j** [gkbm2013/tinker-IO#82]
Forge:
```
forge-1.12.2-14.23.4.2758
```

Error:

```
Time: 8/26/18 5:25 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tinker I/O (tinker_io)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 3
	at java.lang.String.substring(String.java:1963)
	at tinker_io.registry.OreCrusherRecipeRegister.loadFromOreDict(OreCrusherRecipeRegister.java:56)
	at tinker_io.registry.OreCrusherRecipeRegister.init(OreCrusherRecipeRegister.java:19)
	at tinker_io.TinkerIO.postInit(TinkerIO.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
Modlist:

```
 AbyssalCraft-1.12.2-1.9.4.11.jar
 ActuallyAdditions-1.12.2-r140.jar
 AdvancedRocketry-1.12.2-1.4.0-96-universal.jar
 ae2stuff-0.7.0.4-mc1.12.2.jar
 aether_ii-1.12.2-1.0.10.jar
 agricraft-2.12.0-1.12.0-a5.jar
 AkashicTome-1.2-10.jar
 AppleCore-mc1.12.2-3.1.4.jar
 AppleSkin-mc1.12-1.0.9.jar
 appliedenergistics2-rv6-alpha-3.jar
 armorplus-1.12.2-11.13.1.41.jar
 Aroma1997Core-1.12.2-2.0.0.0.b156.jar
 Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b77.jar
 AromaBackup-1.12.2-2.1.1.4.b104.jar
 autopackager-1.10a.jar
 AutoPickup-1.12-2.5.jar
 autoplant-1.12-1.0.0.jar
 AutoRegLib-1.3-20.jar
 base-1.12.2-3.10.0.jar
 Baubles-1.12-1.5.2.jar
 bdlib-1.14.3.12-mc1.12.2.jar
 BedBugs-1.12-1.0.1.jar
 BetterAdvancements-1.12.2-0.0.10.54.jar
 BetterBedrockGenerator-1.12-6.1.1.jar
 BetterBuildersWands-1.12-0.12.0.251+d6c4d93.jar
 BetterFoliage-MC1.12-2.1.10.jar
 BetterQuesting-3.5.263.jar
'BetterSprinting  MC-1.12.2  v2.1.1.jar'
'BiblioCraft[v2.4.5][MC1.12.2].jar'
 BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar
 BloodArsenal-1.12.2-2.1.0-24.jar
 BloodMagic-1.12.2-2.3.1-99.jar
 Bookshelf-1.12.2-2.3.557.jar
'Botania r1.10-354.jar'
 BrandonsCore-1.12.2-2.4.4.173-universal.jar
 buildcraft-7.99.17.jar
 calculator-1.12.2-5.0.8-4.jar
 Cavern_1.12.2-v1.10.6.jar
 Chameleon-1.12-4.1.3.jar
 ChickenChunks-1.12.2-2.4.1.73-universal.jar
 Chisel-MC1.12.2-0.2.0.31.jar
 Clumps-3.1.1.jar
 CodeChickenLib-1.12.2-3.2.1.351-universal.jar
 CoFHCore-1.12.2-4.5.3.20-universal.jar
 CoFHWorld-1.12.2-1.2.0.5-universal.jar
 compactmachines3-1.12.2-3.0.12-b215.jar
 CookingForBlockheads_1.12.2-6.4.44.jar
 CraftingTweaks_1.12.2-8.1.9.jar
 CTM-MC1.12.2-0.3.2.18.jar
 Cyclic-1.12.2-1.16.10.jar
 CyclopsCore-1.12.2-0.11.9.jar
 DarkUtils-1.12.2-1.8.211.jar
 DeathQuotes-1.2.0-mc1.12-forge.jar
 Decocraft-2.6.1_1.12.2.jar
 Draconic-Evolution-1.12.2-2.3.13.306-universal.jar
 embers-0.230.jar
 Enchiridion-1.12.2-3.3.3.jar
 EnderCompass-1.12-1.2.6.2.jar
 EnderCore-1.12.2-0.5.37.jar
 EnderIO-1.12.2-5.0.31.jar
 EnderStorage-1.12.2-2.4.5.135-universal.jar
 enderutilities-1.12.2-0.7.11.jar
 environmentaltech-1.12.2-2.0.15.1.jar
 EverlastingAbilities-1.12.2-1.3.17.jar
 EvilCraft-1.12.2-0.10.63.jar
 extrautils2-1.12-1.8.5.jar
 FastLeafDecay-v14.jar
 FloodLights-1.12.2-1.3.0-1.jar
 fluxnetworks-1.12.2-3.0.16-11.jar
 forestry_1.12.2-5.8.1.339.jar
 Forgelin-1.7.4.jar
 ForgeMultipart-1.12.2-2.5.0.71-universal.jar
 FTBLib-5.3.0.42.jar
 FTBUtilities-5.3.0.45.jar
 FullscreenWindowed-1.12-1.6.0.jar
 gendustry-1.6.5.8-mc1.12.2.jar
 GravityGun-1.12.2-7.0.1.jar
 Guide-API-1.12-2.1.7-62.jar
 HelpFixer-1.12.1-1.5.18.jar
 HoloInventory-1.12.2-2.1.1.151.jar
 Hwyla-1.8.26-B41_1.12.2.jar
 iChunUtil-1.12.2-7.1.4.jar
 ImmersiveEngineering-0.12-84.jar
 industrialforegoing-1.12.2-1.11.1-206.jar
 infinitylib-1.12.0.jar
 InGameAccountSwitcher-Forge-1.12-7.0.3.jar
 InGameInfoXML-1.12.2-2.8.2.94-universal.jar
 InventoryTweaks-1.64-dev.jar
 IronBackpacks-1.12.2-3.0.8-12.jar
 itemscroller-1.12.2-0.12.0.jar
 IvToolkit-1.3.3-1.12.jar
 jei_1.12.2-4.12.0.215.jar
 jeibees-0.9.0.5-mc1.12.2.jar
 journeymap-1.12.2-5.5.2.jar
 JustEnoughResources-1.12.2-0.8.10.50.jar
'Level Up! 2-1.1.22-1.12.jar'
 LibVulpes-1.12.2-0.2.8-37-universal.jar
 llibrary-1.7.15-1.12.2.jar
 Login_Shield-1.12.2-3-g7c6e7ac.jar
 LootBags-1.12.2-2.5.7.jar
 LunatriusCore-1.12.2-1.2.0.42-universal.jar
 Mantle-1.12-1.3.2.24.jar
 MCA-1.12.x-5.3.1-universal.jar
 mcjtylib-1.12-3.0.4.jar
 MCMultiPart-2.5.1.jar
 Mekanism-1.12.2-9.4.13.349.jar
 MekanismGenerators-1.12.2-9.4.13.349.jar
 MekanismTools-1.12.2-9.4.13.349.jar
 MenuMobs-1.12.2-1.21.jar
 MFFS-1.12.2-4.0.1.0_1.12_cc3a5aa.jar
 MobAmputation-1.12.2-7.0.0.jar
 MobDismemberment-1.12.2-7.0.0.jar
 moreoverlays-1.14-mc1.12.2.jar
'MorePlayerModels_1.12.2(18jan18).jar'
 Morpheus-1.12-3.3.2.jar
 Morph-o-Tool-1.2-16.jar
 mp3spi-1.9.5-1.jar
 MrTJPCore-1.12.2-2.1.3.35-universal.jar
 natura-1.12.2-4.3.2.62.jar
 NaturesCompass-1.12.2-1.5.1.jar
'Neat 1.4-17.jar'
'NoMoreRecipeConflict-0.11(1.12.2).jar'
 NotEnoughIDs-1.5.4.2.jar
 OfflineSkins-1.12.2-v4.jar
 omlib-1.12.2-3.0.0-148.jar
 OpenBlocks-1.12.2-1.7.6.jar
 OpenComputers-MC1.12.2-1.7.2.67.jar
 OpenFM-1.12.2-0.1.0.19.jar
 OpenModsLib-1.12.2-0.11.5.jar
 openmodularturrets-1.12.2-3.0.1-257.jar
 orbis_api-1.12.2-1.1.7.jar
 OverpoweredInventory-1.12-2.3.1.jar
"Pam's HarvestCraft 1.12.2y.jar"
 Ping-1.12.2-1.4.4.jar
 plustic-6.5.2.0.jar
 PortalGun-1.12.2-7.0.2.jar
 practicallogistics2-1.12.2-3.0.4.jar
 ProjectRed-1.12.2-4.9.1.92-Base.jar
 ProjectRed-1.12.2-4.9.1.92-compat.jar
 ProjectRed-1.12.2-4.9.1.92-fabrication.jar
 ProjectRed-1.12.2-4.9.1.92-integration.jar
 ProjectRed-1.12.2-4.9.1.92-lighting.jar
 ProjectRed-1.12.2-4.9.1.92-mechanical.jar
 ProjectRed-1.12.2-4.9.1.92-world.jar
 Psi-r1.1-59.jar
 PTRLib-1.0.2.jar
 QuantumStorage-1.12-4.6.1.jar
 Quark-r1.5-127.jar
 RadixCore-1.12.x-2.2.1-universal.jar
 RandomThings-MC1.12.2-4.2.1.jar
 RebornCore-1.12.2-3.10.0.332-universal.jar
 RecurrentComplex-1.4.7.jar
 RedstoneArsenal-1.12.2-2.5.1.13-universal.jar
 RedstoneFlux-1.12-2.0.2.3-universal.jar
 refinedstorage-1.6.3.jar
 Reliquary-1.12.2-1.3.4.767.jar
 rftools-1.12-7.55.jar
 RoguelikeDungeons-1.12.2-1.8.0.jar
 roots-2-0.104.jar
 Scannable-MC1.12.2-1.6.3.22.jar
 ShadowMC-1.12-3.8.0.jar
 SimplyJetpacks2-1.12.2-2.2.7.45.jar
 sonarcore-1.12.2-5.0.15-13.jar
 StandardExpansion-3.4.145.jar
 StorageDrawers-1.12.2-5.3.7.jar
 Tails-1.12-1.10.0.jar
 TConstruct-1.12.2-2.10.1.87.jar
 TechReborn-1.12.2-2.17.1.786-universal.jar
 Tesla-1.12.2-1.0.63.jar
 tesla-core-lib-1.12.2-1.0.15.jar
 Thaumcraft-1.12.2-6.1.BETA23.jar
 ThaumicInventoryScanning_1.12.2-2.0.10.jar
 TheBetweenlands-3.3.11-universal.jar
 thedragonlib-1.12.2-5.3.0.jar
 ThermalDynamics-1.12.2-2.5.1.14-universal.jar
 ThermalExpansion-1.12.2-5.5.0.29-universal.jar
 ThermalFoundation-1.12.2-2.5.0.19-universal.jar
 thutcore-1.12.2-5.19.7.jar
 thuttech-1.12.2-6.1.3.jar
 TickrateChanger-1.0.14.jar
 tinker_io-1.12.2-rw2.7.0.jar
"Tinkers' Addons-1.12.1-1.0.7.jar"
 TIS-3D-MC1.12.2-1.5.0.34.jar
 TombManyGraves-1.12-4.1.0.jar
 tombmanygraves2api-1.12.2-1.0.0.jar
 Translocators-1.12.2-2.5.1.77-universal.jar
 TrashSlot_1.12.1-8.4.6.jar
 twilightforest-1.12.2-3.8.654-universal.jar
 UniDict-1.12.2-2.7.jar
 valkyrielib-1.12.2-2.0.15.1.jar
 VeinMiner-1.12-0.38.2.647+b31535a.jar
 vorbisspi-1.0.3-1.jar
 WailaHarvestability-mc1.12-1.1.12.jar
 WanionLib-1.12.2-1.5.jar
 Wawla-1.12.2-2.5.257.jar
 YABBA-1.1.2.25.jar
```

**Comment by gkbm2013** [comment]
The bug was fix in rw2.7.0a. Thanks for your report!
