### ISSUE TITLE
Fuel Input Machine Exceptions

### ISSUE THREAD

**Issue by Alexis-Grimm** [gkbm2013/tinker-IO#96]
Whenever a smeltery using a fuel input machine with any fuel will cause the server to throw multiple exceptions, now I haven't seen this actually cause any practical issues but it does clog the server log and i just wanted to make sure that you knew about it.

Minecraft Version 1.12.2
Forge Version: 14.23.5.2838
Tinker I/O: 1.12.2-rw2.7.1
Tinker's Construct: 1.12.2-2.12.0.157

**Comment by gkbm2013** [comment]
Could you provide more information about the Exception? Thanks!

**Comment by gkbm2013** [comment]
The issue was closed due to no further discussion.

**Comment by cwc02777** [comment]
作者您好: 我也有相同的問題
Minecraft Version 1.12.2
Forge Version: 14.23.5.2854
Tinker I/O: 1.12.2-rw2.8.3
Tinker's Construct: 1.12.2-2.13.0.183

[02:26:09] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
java.lang.RuntimeException: Missing
	at net.minecraftforge.fml.server.FMLServerHandler.getClientToServerNetworkManager(FMLServerHandler.java:299) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.getClientToServerNetworkManager(FMLCommonHandler.java:555) ~[FMLCommonHandler.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$10.selectNetworks(FMLOutboundHandler.java:329) ~[FMLOutboundHandler$OutboundTarget$10.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[MessageToMessageEncoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToServer(SimpleNetworkWrapper.java:321) [SimpleNetworkWrapper.class:?]
	at tinker_io.network.NetworkHandler.sendToServer(NetworkHandler.java:26) [NetworkHandler.class:?]
	at tinker_io.tileentity.TileEntityFuelInputMachine.setSmelteryTemp(TileEntityFuelInputMachine.java:175) [TileEntityFuelInputMachine.class:?]
	at tinker_io.tileentity.TileEntityFuelInputMachine.burnSolidFuel(TileEntityFuelInputMachine.java:88) [TileEntityFuelInputMachine.class:?]
	at tinker_io.tileentity.TileEntityFuelInputMachine.func_73660_a(TileEntityFuelInputMachine.java:62) [TileEntityFuelInputMachine.class:?]
	at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38) [McHooks.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1838) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**Comment by gkbm2013** [comment]
@cwc02777 
I will figure out what went wrong, thank you for your report.
我會去看看哪邊出了問題，謝謝你的回報~

**Comment by Shuuen-Yukibi** [comment]
作者您好: 燃料輸入機出現異常
MINECRAFT 1.12.2
tinker_io-1.12.2-rw2.8.3.jar
FORGE-14.23.5.2855
多人伺服端
放入燃料後依舊顯示"缺少固體燃料"
模組本身自帶的固體燃料和原版有的燃料都不行
